Update jenkins build

diff --git a/jenkins_build b/jenkins_build
--- a/jenkins_build
+++ b/jenkins_build
@@ -59,6 +59,7 @@ if test "${job_name}" = "master branch"; then
 
     ( cd impatient-guide && cp -f _build/latex/NXImpatient.pdf ${WWW_ROOT}/doc/NXImpatient.pdf && rm -rf ${WWW_ROOT}/doc/impatient && cp -rf _build/html ${WWW_ROOT}/doc/impatient )
 
+fi
     ## new gh-pages stuff
 
     git_rev=`git rev-parse --short HEAD`
@@ -76,8 +77,19 @@ if test "${job_name}" = "master branch"; then
     cp -fr examples ${DIST_ROOT}
 
     cd ..
-    make latexpdf
-    cd build
+    # be more deliberate about building the PDF
+    # first, build all intermediate content, indices, etc.
+    make latex
+    cd build/latex/
+    # next, build the PDF
+    # extra option needed to satisfy "levels nested too deeply" error
+    # expect it to fail (thus exit 0) since nexus.ind not found first time
+    ( pdflatex --interaction=nonstopmode nexus.tex || exit 0 )
+    # make the .ind file now
+    makeindex nexus.idx
+    # run again with fresh nexus.ind
+    ( pdflatex --interaction=nonstopmode nexus.tex || exit 0 )
+    cd ..
 
     #pdf
     cp -f latex/nexus.pdf ${DIST_ROOT}/pdf/NeXusManual.pdf
@@ -97,6 +109,5 @@ if test "${job_name}" = "master branch"; then
     git commit -m "Update docs for ${git_rev}"
     git push origin gh-pages
 
-fi
 
 exit 0
