Update nexus-fairmat-gen-docs.yml
restricted workflow to treat only pushes on the fairmat branch and support for manual triggering of the action

diff --git a/.github/workflows/nexus-fairmat-gen-docs.yml b/.github/workflows/nexus-fairmat-gen-docs.yml
--- a/.github/workflows/nexus-fairmat-gen-docs.yml
+++ b/.github/workflows/nexus-fairmat-gen-docs.yml
@@ -1,153 +1,98 @@
-name: Generate Webpage
-
-on: # push
+name: NeXus/FAIRmat-Experimental Sphinx Docs to GitHub Pages
+on:
   #push:
-  #  branches: [ main ]
-  #pull_request:
-  #  branches: [ main ]
-  # if you would like to trigger manually the execution of this workflow (e.g. from the actions tab)
+  #  branches:
+  #    - fairmat
   workflow_dispatch:
 
+# see: https://sphinx-notes.github.io/pages/
+# see: https://github.com/marketplace/actions/sphinx-to-github-pages
+
 jobs:
-  nexus-fairmat-manual-gen:
+
+  build:
     runs-on: ubuntu-latest
+
     steps:
-      #
-      #- id: addKey
-      #  name: Add key for staging push
-      #  uses: webfactory/ssh-agent@ee29fafb6aa450493bac9136b346e51ea60a8b5e
-      #  with:
-      #    ssh-private-key: ${{ secrets.STAGING_KEY }}
+    - name: Checkout
+      uses: actions/checkout@master
+      with:
+        fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
 
-      #- uses: mshick/add-pr-comment@v1
-      #  if: ${{ failure()  && steps.addKey.conclusion == 'failure' }}
-      #  with:
-      #    message: "Staging key could not be imported, cannot push to
-      #      oscovida/staging to create test website instance. If this PR is
-      #      external it may not have access to the required secrets."
-      #    repo-token: ${{ secrets.GITHUB_TOKEN }}
-      #    repo-token-user-login: 'github-actions[bot]'
-      #    allow-repeats: false
+    - name: Install build requirements
+      run: |
+        pip install -r requirements.txt
+    - name: Diagnostic
+      run: |
+        pip list
+    - name: Run the test suite
+      run: |
+        # stops publishing when known problems are found
+        python utils/test_suite.py
+    - name: Prepare for out-of-source Sphinx build
+      run: |
+        rm -rf ./build
+        mkdir ./build
+        python ./utils/build_preparation.py . ./build
+    - name: Diagnostic
+      run: |
+        ls -lAFGh
+        ls -lAFGh ./build
+    - name: Install LaTeX
+      run: |
+        sudo apt-get update -y && \
+        sudo apt-get install -y \
+          latexmk \
+          texlive-latex-recommended \
+          texlive-latex-extra \
+          texlive-fonts-recommended
+    - name: Build impatient guide
+      run: |
+        make -C ./build/impatient-guide html latexpdf
+        ls -lAFGh ./build/impatient-guide/_build/latex/*.pdf
+        # Copy to documentation source directory
+        cp \
+          ./build/impatient-guide/_build/latex/NXImpatient.pdf \
+          ./build/manual/source/_static/
+    - name: Build PDF of manual
+      run: |
+        # expect next make (PDF) to fail (thus exit 0)
+        # since nexus.ind not found first time
+        # extra option for "levels nested too deeply" error
+        ( \
+          make latexpdf \
+            LATEXOPTS="--interaction=nonstopmode" \
+            -C build/manual \
+          || exit 0 \
+        )
+        # make that missing file
+        makeindex build/manual/build/latex/nexus.idx
+        # build the PDF, still a failure will be noted
+        # but we can ignore it without problem
+        ( \
+          make latexpdf \
+            LATEXOPTS="--interaction=nonstopmode" \
+            -C build/manual \
+          || exit 0\
+        )
+        # Copy to documentation source directory
+        cp \
+          ./build/manual/build/latex/nexus.pdf \
+          ./build/manual/source/_static/NeXusManual.pdf
+    - name: Include other PDFs
+      run: |
+        wget https://github.com/nexusformat/code/raw/master/doc/api/NeXusIntern.pdf -O ./build/manual/source/_static/NeXusIntern.pdf
+        wget https://github.com/nexusformat/code/raw/master/applications/NXtranslate/docs/NXtranslate.pdf -O ./build/manual/source/_static/NXtranslate.pdf
+    - name: Build (html) and Commit
+      uses: sphinx-notes/pages@master
+      with:
+        # path to conf.py directory
+        documentation_path: build/manual/source
 
-      #- name: Early exit for missing staging keys
-      #  if: ${{ failure() && steps.addKey.conclusion == 'failure' }}
-      #  uses: andymckay/cancel-action@0.2
-
-      - name: Set up Python 3.9
-        uses: actions/setup-python@v2
-        with:
-          python-version: 3.9
-          # persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
-          # fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
-
-      #- name: Checkout oscovida/staging
-      #  uses: actions/checkout@v2
-      #  with:
-      #    ssh-key: ${{ secrets.STAGING_KEY }}
-      #    repository: oscovida/staging
-      #    persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
-      #    fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
-
-      #- name: Checkout oscovida pr branch
-      #  uses: actions/checkout@v2
-      #  with:
-      #    path: oscovida
-      #    ref: ${{ github.event.pull_request.head.sha }}
-
-      #- name: Set up oscovida and webgen
-      #  run: |
-      #    pip install ./oscovida
-      #    pip install -r ./base/requirements.txt
-      #- name: Run pre-generate hook
-      #  run: |
-      #    ./oscovida/tools/oscovida.github.io/pre-generate.sh
-      #- name: Generate new reports
-      #  run: |
-      #    export PR_NO=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
-      #    cp -r ./base $PR_NO
-      #    export WWWROOT=$(readlink -f $PR_NO)
-      #    echo $WWWROOT
-      #    cd ./oscovida/tools/
-      #    ln -s $WWWROOT ./wwwroot
-      #    ls ./wwwroot
-      #    python3 -m report_generators.cli --debug \
-      #      --regions=all  \
-      #      --workers=max  \
-      #      --log-level=INFO  \
-      #      --log-file=./wwwroot/report-gen.log
-      #- name: Run post-generate hook
-      #  run: |
-      #    ./oscovida/tools/oscovida.github.io/post-generate.sh
-  
-      - name: Update pip and install sphinx and required tools
-        run: |
-          echo $GITHUB_WORKSPACE
-          pip install --upgrade pip
-          pip install lxml Sphinx sphinx_comments pyRestTable six
-        
-      - name: Pull the state of the source repo, i.e. the one with the rst source code
-        run: |
-          cd $GITHUB_WORKSPACE
-          # mkdir -p source
-          # cd source
-          # ls $PWD
-          # git clone https://github.com/Tommaso-Pincelli/definitions.git
-          #git clone git@github.com:Tommaso-Pincelli/definitions.git
-          #cd definitions
-          make all
-          #cd $GITHUB_WORKSPACE
-          #mkdir -p target
-          #cd target
-          #ls $PWD
-          #git clone https://github.com/mkuehbach/definitions.github.io.git
-          #git clone git@github.com:mkuehbach/definitions.github.io.git
-          #cd definitions.github.io/docs
-          #echo "Carrying changes over to local version of the repo!"
-          cp -R $GITHUB_WORKSPACE/source/definitions/manual/build/html $GITHUB_WORKSPACE/docs/
-          ##currently in the target repo
-          ls $PWD
-          #git config --global user.name "GitHub Actions Bot"
-          #git config --global user.email "<>"
-          #cd $GITHUB_WORKSPACE/target/definitions.github.io
-          #echo $GITHUB_EMAIL
-          #echo $GITHUB_USERNAME
-          #echo ${{ github.actor }}
-          #git config --global user.email "$GITHUB_EMAIL"
-          #git config --global user.name "$GITHUB_USERNAME"
-          #git config user.email "markus.kuehbach@rwth-aachen.de"
-          #git config user.name ${{ github.actor }}
-          #git config user.name ${{ secrets.GH_USER }}
-          #git config user.email "${{ secrets.GH_MAIL }}
-          #echo ${{ secrets.GH_USER }}
-          #echo ${{ secrets.GH_MAIL }}
-          #git remote -v
-          #git remote set-url origin git@github.com:/mkuehbach/definitions.github.io.git
-          #git remote -v
-          git add .
-          #git status
-          git commit -m "Auto-committed "
-          git status
-          #REMOTE=https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
-          #echo $REMOTE
-          #git push #${REMOTE} master
-          git push
-
-     #- name: Update HTML pages
-     #   run: |
-     #     source .venv_pelican/bin/activate
-     #     cd ./oscovida/tools/pelican
-     #     make publish
-     # - name: Commit files
-     #   run: |
-     #     export PR_NO=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
-
-     #     git add $PR_NO --all
-     #     git commit -m "Generated preview for PR $PR_NO on $(date)" -a
-     #     git push
-     # - uses: mshick/add-pr-comment@v1
-     #   with:
-     #     message: "View web reports generated with this branch at
-     #       [staging/${{ github.event.number }}/](https://oscovida.github.io/staging/${{ github.event.number }}/index.html)"
-     #     repo-token: ${{ secrets.GITHUB_TOKEN }}
-     #     repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
-     #     allow-repeats: false # This is the default
+    - name: Publish if refs/tags
+      # remove/comment next line to push right away
+      if: startsWith(github.ref, 'refs/tags')
+      uses: ad-m/github-push-action@master
+      with:
+        github_token: ${{ secrets.GITHUB_TOKEN }}
+        branch: gh-pages
