MNT #953 publish the PDFs, publish if new tag

diff --git a/.github/workflows/publish-sphinx.yml b/.github/workflows/publish-sphinx.yml
--- a/.github/workflows/publish-sphinx.yml
+++ b/.github/workflows/publish-sphinx.yml
@@ -25,6 +25,7 @@ jobs:
 
     - name: Run the test suite
       run: |
+        # stops publishing when known problems are found
         python utils/test_suite.py
 
     - name: Prepare for out-of-source Sphinx build
@@ -51,25 +52,41 @@ jobs:
       run: |
         make -C ./build/impatient-guide html latexpdf
         ls -lAFGh ./build/impatient-guide/_build/latex/*.pdf
-        # TODO: copy ?
+
+        # Copy to documentation source directory
+        cp \
+          ./build/impatient-guide/_build/latex/NXImpatient.pdf \
+          ./build/manual/source/_static/
 
     - name: Build PDF of manual
       run: |
-        # expect next make (PDF) to fail (thus exit 0) since nexus.ind not found first time
-        # extra option needed to satisfy "levels nested too deeply" error
-        (make latexpdf LATEXOPTS="--interaction=nonstopmode" -C build/manual || exit 0)
+        # expect next make (PDF) to fail (thus exit 0)
+        # since nexus.ind not found first time
+
+        # extra option for "levels nested too deeply" error
+        ( \
+          make latexpdf \
+            LATEXOPTS="--interaction=nonstopmode" \
+            -C build/manual \
+          || exit 0 \
+        )
+
         # make that missing file
         makeindex build/manual/build/latex/nexus.idx
-        # build the PDF, still a failure will be noted but we can ignore it without problem
-        (make latexpdf LATEXOPTS="--interaction=nonstopmode" -C build/manual || exit 0)
 
-        # TODO: copy ?
+        # build the PDF, still a failure will be noted
+        # but we can ignore it without problem
+        ( \
+          make latexpdf \
+            LATEXOPTS="--interaction=nonstopmode" \
+            -C build/manual \
+          || exit 0\
+        )
 
-    - name: Diagnostic
-      run: |
-        echo "HTML built: `ls -lAFgh build/manual/build/html/*.html`"
-        echo "PDF built: `ls -lAFgh build/manual/build/latex/*.pdf`"
-        ls -lAFGh ./build/manual/build/latex/*
+        # Copy to documentation source directory
+        cp \
+          ./build/manual/build/latex/nexus.pdf \
+          ./build/manual/source/_static/NeXusManual.pdf
 
     - name: Build (html) and Commit
       uses: sphinx-notes/pages@master
@@ -77,9 +94,10 @@ jobs:
         # path to conf.py directory
         documentation_path: build/manual/source
 
-    # - name: Push changes if refs/tags
-    #   if: startsWith(github.ref, 'refs/tags')
-    #   uses: ad-m/github-push-action@master
-    #   with:
-    #     github_token: ${{ secrets.GITHUB_TOKEN }}
-    #     branch: gh-pages
+    - name: Push changes if refs/tags
+      # remove/comment next line to push right away
+      if: startsWith(github.ref, 'refs/tags')
+      uses: ad-m/github-push-action@master
+      with:
+        github_token: ${{ secrets.GITHUB_TOKEN }}
+        branch: gh-pages
